version: '3.8'

volumes:
  n8n_db_storage:
  n8n_storage:
  n8n_redis_storage:
  caddy_data:
  caddy_config:
  structify_db_storage:
  seafile_db:
  seafile_data:
  pihole_data:
  dnsmasq_data:

networks:
  # Internal network for DB/Redis n8n communication
  n8n_internal_bridge:
    driver: bridge
  cv_react_internal_bridge:
    driver: bridge
  structify_bridge:
    driver: bridge
  seafile_net:
    driver: bridge
  # Reference the macvlan network created via CLI
  macvlan:
    external: true

x-shared: &shared
  restart: always
  image: docker.n8n.io/n8nio/n8n
  environment:
    - DB_TYPE=postgresdb
    - DB_POSTGRESDB_HOST=n8n_postgres
    - DB_POSTGRESDB_PORT=5432
    - DB_POSTGRESDB_DATABASE=${N8N_POSTGRES_DB}
    - DB_POSTGRESDB_USER=${N8N_POSTGRES_USER}
    - DB_POSTGRESDB_PASSWORD=${N8N_POSTGRES_PASSWORD}
    - EXECUTIONS_MODE=queue
    - QUEUE_BULL_REDIS_HOST=n8n_redis
    - QUEUE_HEALTH_CHECK_ACTIVE=true
    - N8N_ENCRYPTION_KEY=Avenue4060
    - N8N_PROTOCOL=https
    - WEBHOOK_URL=https://n8n.damiankaplon.site/
  volumes:
    - n8n_storage:/home/node/.n8n
  networks:
    - n8n_internal_bridge
  depends_on:
    n8n_redis:
      condition: service_healthy
    n8n_postgres:
      condition: service_healthy

services:
  n8n_postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_USER=${N8N_POSTGRES_USER}
      - POSTGRES_PASSWORD=${N8N_POSTGRES_PASSWORD}
      - POSTGRES_DB=${N8N_POSTGRES_DB}
    volumes:
      - n8n_db_storage:/var/lib/postgresql/data
    networks:
      - n8n_internal_bridge
    healthcheck:
      test: [ 'CMD-SHELL', 'pg_isready -h localhost -U poplar3080 -d n8n' ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n_redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - n8n_redis_storage:/data
    networks:
      - n8n_internal_bridge
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    <<: *shared
    networks:
      - n8n_internal_bridge

  caddy:
    image: my-caddy:latest
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CLOUDFLARE_API_TOKEN=${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
      - ./origin.pem:/etc/ssl/caddy/origin.pem
      - ./origin.key:/etc/ssl/caddy/origin.key
      - ./auth-app-origin.pem:/etc/ssl/caddy/auth-app-origin.pem
      - ./auth-app-origin.key:/etc/ssl/caddy/auth-app-origin.key

    networks:
      n8n_internal_bridge:
      cv_react_internal_bridge:
      structify_bridge:
      seafile_net:
      macvlan:
        ipv4_address: 192.168.0.230
    depends_on:
      - n8n
  
  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: always
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TUNNEL_TOKEN}
    command: tunnel run
    networks:
      - n8n_internal_bridge

  cv-react:
    image: cv-react:1.0.0
    container_name: cv-react
    restart: always
    networks:
      - cv_react_internal_bridge

  n8n-worker:
    <<: *shared
    command: worker

  structify_postgres:
    image: postgres:16
    restart: always
    environment:
      - POSTGRES_DB=${STRUCTIFY_POSTGRES_DB}
      - POSTGRES_USER=${STRUCTIFY_POSTGRES_USER}
      - POSTGRES_PASSWORD=${STRUCTIFY_POSTGRES_PASSWORD}
      - KC_DB_USER=${KC_DB_USER}
      - KC_DB_PASS=${KC_DB_PASS}
      - KC_DB_NAME=${KC_DB_NAME}
    volumes:
      - structify_db_storage:/var/lib/postgresql/data
      - ./structify/db:/docker-entrypoint-initdb.d
    networks:
      - structify_bridge

  structify_keycloak:
    image: kc:latest
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://structify_postgres/keycloak
      KC_DB_USERNAME: ${STRUCTIFY_POSTGRES_USER}
      KC_DB_PASSWORD: ${STRUCTIFY_POSTGRES_PASSWORD}
      KC_PROXY_HEADERS: xforwarded
      KC_HOSTNAME: ${STRUCTIFY_KC_HOSTNAME}
      KC_HOSTNAME_DEBUG: true
      KEYCLOAK_ADMIN: ${STRUCTIFY_KC_ADMIN_USER}
      KEYCLOAK_ADMIN_PASSWORD: ${STRUCTIFY_KC_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: true
    command: start --optimized
    networks:
      - structify_bridge
    depends_on:
      - structify_postgres

  structify_app:
    image: structify:7
    container_name: structify_app
    restart: always
    environment:
      APP_CHATGPT_API_KEY: ${CHATGPT_API_KEY}
      APP_STRUCTIFY_UI_HOSTED: ${STRUCTIFY_UI_HOSTED}
      APP_STRUCTIFY_OAUTH_AUTH_URL: ${STRUCTIFY_OAUTH_AUTH_URL}
      APP_STRUCTIFY_OAUTH_REDIRECT_URL: ${STRUCTIFY_OAUTH_REDIRECT_URL}
      APP_STRUCTIFY_ACCESS_TOKEN_URL: ${STRUCTIFY_ACCESS_TOKEN_URL}
      APP_STRUCTIFY_CLIENT_ID: ${STRUCTIFY_CLIENT_ID}
      APP_STRUCTIFY_SECRET: ${STRUCTIFY_SECRET}
      APP_STRUCTIFY_LOG_OUT: ${STRUCTIFY_LOG_OUT}
      APP_STRUCTIFY_JWK_URL: ${STRUCTIFY_JWK_URL}
      APP_STRUCTIFY_ISSUER: ${STRUCTIFY_ISSUER}
      APP_STRUCTIFY_DB_URL: ${STRUCTIFY_DB_URL}
      APP_STRUCTIFY_DB_USER: ${STRUCTIFY_DB_USER}
      APP_STRUCTIFY_DB_PASS: ${STRUCTIFY_DB_PASS}
      APP_STRUCTIFY_DB_SCHEMA: ${STRUCTIFY_DB_SCHEMA}
    networks:
      - structify_bridge
    depends_on:
      - structify_postgres
      - structify_keycloak

  seafile-mysql:
    image: mariadb:10.11
    container_name: seafile-mysql
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD}
      - MYSQL_LOG_CONSOLE=true
      - MARIADB_AUTO_UPGRADE=1
    volumes:
      - "seafile_db:/var/lib/mysql"
    networks:
      - seafile_net
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--connect",
          "--mariadbupgrade",
          "--innodb_initialized",
        ]
      interval: 20s
      start_period: 30s
      timeout: 5s
      retries: 10

  seafile-redis:
    image: redis
    container_name: seafile-redis
    restart: unless-stopped
    command:
      - /bin/sh
      - -c
      - redis-server --requirepass "$$REDIS_PASSWORD"
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    networks:
      - seafile_net

  seafile:
    image: seafileltd/seafile-mc:13.0-latest
    container_name: seafile
    restart: unless-stopped
    volumes:
      - seafile_data:/shared
    environment:
      - SEAFILE_MYSQL_DB_HOST=seafile-mysql
      - SEAFILE_MYSQL_DB_PORT=3306
      - SEAFILE_MYSQL_DB_USER=seafile
      - SEAFILE_MYSQL_DB_PASSWORD=${SEAFILE_MYSQL_DB_PASSWORD:?Variable is not set or empty}
      - INIT_SEAFILE_MYSQL_ROOT_PASSWORD=${INIT_SEAFILE_MYSQL_ROOT_PASSWORD}
      - SEAFILE_MYSQL_DB_CCNET_DB_NAME=${SEAFILE_MYSQL_DB_CCNET_DB_NAME:-ccnet_db}
      - SEAFILE_MYSQL_DB_SEAFILE_DB_NAME=${SEAFILE_MYSQL_DB_SEAFILE_DB_NAME:-seafile_db}
      - SEAFILE_MYSQL_DB_SEAHUB_DB_NAME=${SEAFILE_MYSQL_DB_SEAHUB_DB_NAME:-seahub_db}
      - TIME_ZONE=Europe/Warsaw
      - INIT_SEAFILE_ADMIN_EMAIL=${INIT_SEAFILE_ADMIN_EMAIL}
      - INIT_SEAFILE_ADMIN_PASSWORD=${INIT_SEAFILE_ADMIN_PASSWORD}
      - SEAFILE_SERVER_HOSTNAME=${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      - SEAFILE_SERVER_PROTOCOL=https
      - JWT_PRIVATE_KEY=${JWT_PRIVATE_KEY:?Variable is not set or empty}
      - SEAFILE_LOG_TO_STDOUT=false
      - ENABLE_GO_FILESERVER=true
      - CACHE_PROVIDER=redis
      - REDIS_HOST=${REDIS_HOST:-seafile-redis}
      - REDIS_PORT=${REDIS_PORT:-6379}
      - REDIS_PASSWORD=${REDIS_PASSWORD:-}
      - ENABLE_NOTIFICATION_SERVER=false
      - MD_FILE_COUNT_LIMIT=${MD_FILE_COUNT_LIMIT:-100000}
    labels:
      caddy: ${SEAFILE_SERVER_PROTOCOL:-https}://${SEAFILE_SERVER_HOSTNAME:?Variable is not set or empty}
      caddy.reverse_proxy: "{{upstreams 80}}"
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:80 || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      seafile-mysql:
        condition: service_healthy
      seafile-redis:
        condition: service_started
    networks:
      - seafile_net
  pihole:
    image: pihole/pihole:latest
    container_name: pihole
    restart: always
    # NET_ADMIN is strictly required for Pi-hole to act as a DHCP server
    cap_add:
      - NET_ADMIN
    environment:
      - TZ=Europe/Warsaw
      - FTLCONF_webserver_api_password:=${PIHOLE_WEBPASSWORD}
    volumes:
      - pihole_data:/etc/pihole
      - dnsmasq_data:/etc/dnsmasq.d
    networks:
      macvlan:
        # Assign a free static IP on your LAN. I used .231 assuming Caddy is .230
        ipv4_address: 192.168.0.231

  qrcodegen:
    image: ktor-qrcodegen
    container_name: qrcodegen
    restart: always
    networks:
      - n8n_internal_bridge

  ocr-api:
    image: receipt-ocr-api
    container_name: ocr-api
    restart: always
    networks:
      - n8n_internal_bridge
